/* Quay 1 Boarding Tool - single-page app.
 *
 * Three sections behind the Supabase JWT gate (auth.js): Onboard (contract
 * request + provisioning checkboxes, POST kind:'onboard_quay1'|'onboard_aqua'),
 * Provisioning status (live queue table, POST kind:'status', super-only retry
 * via kind:'retry') and Offboard (pick a person, confirm, POST kind:'offboard'
 * - backend fires the teardown +30 min, no cancel).
 *
 * All backend calls POST text/plain (no CORS preflight) to LIFECYCLE_ENDPOINT
 * with body { kind, accessToken, ...fields } - the Supabase JWT + payload at the
 * top level. The backend re-verifies the JWT + role on every write, so this
 * UI gate is convenience only. Kinds come from docs/ARCHITECTURE.md section 3
 * and are centralised in the KINDS const so they track one place.
 */
(() => {
  'use strict';

  const cfg = window.QUAY_CFG || {};
  const ENDPOINT = cfg.LIFECYCLE_ENDPOINT || '';

  // Router dispatch kinds (docs/ARCHITECTURE.md section 3, confirmed by
  // architect). Onboard splits by entity into two kinds. One place to retune.
  const KINDS = {
    onboardQuay1: 'onboard_quay1',
    onboardAqua: 'onboard_aqua',
    approve: 'approve',
    remind: 'remind',
    resendPacket: 'resend_packet',
    status: 'status',
    programs: 'programs',
    retry: 'retry',
    offboard: 'offboard',
    offboardNotify: 'offboard_notify',
  };

  // Provisioning systems (docs/CONTRACTS.md section 6). google/propdata are the
  // core stack, checked by default. cma/dialfire are optional and auto-check when
  // the matching broker program is ticked on the Quay 1 form. (Property24 is no
  // longer provisioned by this tool - removed at the client's request.)
  const SYSTEMS = [
    { key: 'google',     label: 'Google Workspace', sub: 'account + groups', core: true },
    { key: 'propdata',   label: 'PropData',         sub: 'agent profile',    core: true },
    { key: 'cma',        label: 'CMA',               sub: 'valuation login' },
    { key: 'dialfire',   label: 'Dialfire',          sub: 'dialer seat' },
  ];

  // Broker Activities (Quay 1) - the residential clause options from the Broker Agreement
  // template. Mirrors CFG.BROKER_ACTIVITIES on the backend AND the live recruitment frontend
  // (quay-hubspot). `code` is submitted; the backend merges the matching clause into the contract
  // and derives Sale vs Rental from it (rent_* -> Rental). Commercial is parked (no template yet).
  const BROKER_ACTIVITIES = [
    { code: 'sell_res_sb', label: 'Sell · Residential · Broker (SB)' },
    { code: 'sell_res_jb', label: 'Sell · Residential · Assistant (JB)' },
    { code: 'rent_res_sb', label: 'Rent · Residential · Broker (SB)' },
    { code: 'rent_res_jb', label: 'Rent · Residential · Assistant (JB)' },
  ];

  const OFFBOARD_DELAY_MIN = 30;

  // Division directory (teams + senior brokers), loaded once from the static data file the
  // dashboards share (data/divisions.json, generated by quay-hubspot/scripts/parse_divisions.py).
  // Feeds the Quay 1 Team dropdown (grouped by section) and auto-fills the senior broker.
  let _divisions = null;         // cached ONLY on a successful, non-empty load (see below)
  let _divisionsLoading = null;  // in-flight promise so concurrent renders share one fetch
  // Fetch the division directory. A failure (or empty file) is NOT cached - it resolves to an
  // empty shape for this call but leaves _divisions null, so re-opening the form retries instead
  // of being stuck on a transient blip. Callers fall back to a free-text team field when empty.
  function loadDivisions() {
    if (_divisions) return Promise.resolve(_divisions);
    if (_divisionsLoading) return _divisionsLoading;
    _divisionsLoading = fetch('data/divisions.json', { cache: 'no-cache' })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error('divisions ' + r.status))))
      .then((d) => {
        if (d && Array.isArray(d.sections) && d.sections.length) { _divisions = d; return d; }
        return { sections: [] };                 // valid but empty - don't cache, allow retry
      })
      .catch(() => ({ sections: [] }))           // transient failure - don't cache, allow retry
      .finally(() => { _divisionsLoading = null; });
    return _divisionsLoading;
  }

  // Fill a <select> with teams grouped by division section. Each option carries that TEAM's
  // first-listed broker as the senior (data-senior / data-senior-email). Teams are de-duplicated
  // by name across sections (first wins) so the same team never appears twice.
  function fillTeamOptions(sel, divisions) {
    const secs = (divisions && divisions.sections) || [];
    if (!secs.length) { sel.innerHTML = '<option value="">No teams found</option>'; return; }
    const seen = {};
    let html = '<option value="">- select team -</option>';
    secs.forEach((sec) => {
      const opts = (sec.teams || []).map((t) => {
        const name = String(t.name || '').trim();
        if (!name || seen[name.toLowerCase()]) return '';
        seen[name.toLowerCase()] = true;
        const sb = (t.brokers && t.brokers[0]) || {};
        return `<option value="${esc(name)}" data-senior="${esc(sb.name || '')}"`
          + ` data-senior-email="${esc(sb.email || '')}">${esc(name)}</option>`;
      }).filter(Boolean).join('');
      if (opts) html += `<optgroup label="${esc(sec.name || 'Teams')}">${opts}</optgroup>`;
    });
    sel.innerHTML = html;
  }

  // Availability fallback: when divisions.json is unreachable or empty, swap the Team <select>
  // (whose only option would be a blank placeholder, making a required field unsubmittable) for a
  // free-text <input> of the same name, so a broker onboarding can still be created by typing the
  // team. Senior fields then stay manually editable (no auto-fill source without the directory).
  function degradeTeamToText(sel) {
    if (!sel || !sel.parentNode) return;
    const req = sel.hasAttribute('aria-required');
    const input = document.createElement('input');
    input.id = sel.id; input.name = sel.name; input.type = 'text'; input.autocomplete = 'off';
    input.placeholder = 'Type the team name';
    if (req) input.setAttribute('aria-required', 'true');
    sel.replaceWith(input);
  }

  // ── DOM helpers ───────────────────────────────────────────────────────────
  const $ = (sel, root = document) => root.querySelector(sel);
  const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  function el(html) { const t = document.createElement('template'); t.innerHTML = html.trim(); return t.content.firstElementChild; }

  let USER = null;              // logged-in staff (from AUTH.getSession)
  let statusCache = [];         // last provisioning-status rows (feeds offboard picker)

  // ── Toast ─────────────────────────────────────────────────────────────────
  function toast(title, body, kind) {
    const host = $('#toastHost');
    const node = el(`<div class="toast ${kind || ''}" role="status">
      <strong>${esc(title)}</strong>${body ? esc(body) : ''}</div>`);
    host.appendChild(node);
    setTimeout(() => { node.style.opacity = '0'; setTimeout(() => node.remove(), 250); }, 5200);
  }

  // ── API ───────────────────────────────────────────────────────────────────
  // POST text/plain so no CORS preflight fires. Body is { kind, accessToken,
  // ...fields } (docs/CONTRACTS.md section 7): the Supabase JWT rides as
  // `accessToken` and the payload fields sit at the top level alongside kind.
  const API_TIMEOUT_MS = 35000;  // a wedged Apps Script POST must surface as an error, never an eternal spinner

  async function api(kind, data) {
    if (!ENDPOINT) throw new Error('LIFECYCLE_ENDPOINT not set in config.js');
    const accessToken = await window.AUTH.getAccessToken();
    if (!accessToken) throw new Error('Session expired, sign in again.');
    // AbortController gives every call a hard ceiling: if the backend stalls, the fetch rejects
    // (caught by callers) instead of hanging forever and freezing the view on a spinner.
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), API_TIMEOUT_MS);
    let res;
    try {
      res = await fetch(ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' },
        body: JSON.stringify(Object.assign({ kind, accessToken }, data || {})),
        signal: ctrl.signal,
      });
    } catch (err) {
      throw new Error(err && err.name === 'AbortError' ? 'The server took too long to respond. Please try again.' : 'Could not reach the server. Check your connection and try again.');
    } finally {
      clearTimeout(timer);
    }
    let json;
    try { json = await res.json(); } catch (_) { throw new Error('Bad response from server.'); }
    if (!res.ok || json.ok === false) throw new Error(json && json.error ? json.error : 'Request failed.');
    return json;
  }

  // Shared surface for split view modules. The Offboard view lives in its own
  // file (app.offboard.js) to keep this file under the 500-line cap; it reaches
  // the shared helpers + mutable state through here. No behaviour change - the
  // getters/setters read and write the same closure variables as before.
  const HUB = (window.HUB = window.HUB || {});
  HUB.$ = $; HUB.esc = esc; HUB.el = el; HUB.api = api; HUB.toast = toast;
  HUB.KINDS = KINDS; HUB.OFFBOARD_DELAY_MIN = OFFBOARD_DELAY_MIN;
  // Shared pipeline-card pieces, so the Progress report (renderPipeline) and the Admin Check tab
  // (app.admincheck.js) render the same new hire identically and never drift.
  HUB.docPill = (on, label) => `<span class="doc-tick${on ? '' : ' missing'}">${esc(label)}</span>`;
  HUB.entTag = (ent) => String(ent || '').toLowerCase() === 'aqua'
    ? '<span class="tag-entity tag-aqua">Aqua</span>' : '<span class="tag-entity tag-quay1">Quay 1</span>';
  // Initial-badge for queue/pipeline cards (up to two initials of the name). app.admincheck.js
  // reuses this so both tabs render the same new hire identically.
  HUB.avatar = (name, ent) => {
    const initials = String(name || '').trim().split(/\s+/).filter(Boolean)
      .slice(0, 2).map((w) => w[0].toUpperCase()).join('') || '?';
    const aqua = String(ent || '').toLowerCase() === 'aqua' ? ' avatar-aqua' : '';
    return `<span class="avatar${aqua}">${esc(initials)}</span>`;
  };
  HUB.getUser = () => USER;
  HUB.getStatusCache = () => statusCache;
  HUB.setStatusCache = (v) => { statusCache = v; };

  //  ROUTER
  const VIEWS = {
    onboard: viewOnboard, provisioning: viewProvisioning, programs: viewPrograms,
    offboard: (root) => window.HUB.viewOffboard(root),      // defined in app.offboard.js
    admincheck: (root) => window.HUB.viewAdminCheck(root),  // defined in app.admincheck.js
  };

  // Admin Check (accept FICA -> release provisioning + email CMA approvers) is super/admin only.
  const canAdminCheck = () => !!(USER && (USER.isAdmin || USER.isSuper));

  function route(tab) {
    // Brokers cannot open Offboard or Admin Check; bounce them to Onboard.
    if (tab === 'offboard' && !(USER && USER.canOnboard)) tab = 'onboard';
    if (tab === 'admincheck' && !canAdminCheck()) tab = 'onboard';
    document.querySelectorAll('.tab-btn').forEach((b) => {
      const on = b.dataset.tab === tab;
      b.classList.toggle('active', on);
      if (on) b.setAttribute('aria-current', 'page'); else b.removeAttribute('aria-current');
    });
    // Mirror the active state onto the mobile bottom nav (index.html .bottom-nav a[data-tab]).
    document.querySelectorAll('.bottom-nav a[data-tab]').forEach((a) => {
      if (a.dataset.tab === tab) a.setAttribute('aria-current', 'page'); else a.removeAttribute('aria-current');
    });
    const main = $('#content');
    main.innerHTML = '';
    (VIEWS[tab] || viewOnboard)(main);
    main.focus({ preventScroll: true });
  }

  //  1. ONBOARD
  function viewOnboard(root) {
    let entity = 'quay1';

    const wrap = el(`<div class="stack">
      <div class="section-head">
        <h2>Onboard a new person</h2>
        <p>Generate the contract and record the systems to provision. The candidate is emailed their agreement and a secure FICA link. No accounts are created here: once their signed contract and FICA documents are in, an admin accepts them on the Admin Check tab, and accounts are set up then. Fields marked with a red asterisk are required.</p>
      </div>
      <div class="card card-pad stack">
        <div class="segmented" role="tablist" aria-label="Entity">
          <button type="button" role="tab" data-ent="quay1" aria-pressed="true">Quay 1</button>
          <button type="button" role="tab" data-ent="aqua" aria-pressed="false">Aqua Promotions</button>
        </div>
        <form id="onboardForm" novalidate></form>
      </div>
    </div>`);

    const form = $('#onboardForm', wrap);
    const seg = $('.segmented', wrap);
    seg.addEventListener('click', (e) => {
      const b = e.target.closest('button[data-ent]'); if (!b) return;
      entity = b.dataset.ent;
      seg.querySelectorAll('button').forEach((x) => {
        x.setAttribute('aria-pressed', String(x === b));
      });
      renderForm();
    });

    function fieldText(name, label, opts = {}) {
      const req = opts.required ? ' <span class="req" aria-hidden="true">*</span>' : '';
      const type = opts.type || 'text';
      const cls = opts.full ? 'field wide' : 'field';
      const hint = opts.hint ? `<span class="hint">${esc(opts.hint)}</span>` : '';
      const ro = opts.readonly ? ' readonly' : '';
      const ph = opts.placeholder ? ` placeholder="${esc(opts.placeholder)}"` : '';
      return `<div class="${cls}">
        <label for="f_${name}">${esc(label)}${req}</label>
        <input id="f_${name}" name="${name}" type="${type}"${ro}${ph} ${opts.required ? 'aria-required="true"' : ''} autocomplete="off">
        ${hint}<span class="field-err" id="e_${name}" aria-live="polite"></span></div>`;
    }
    function fieldSelect(name, label, options, req) {
      const opts = options.map((o) => `<option value="${esc(o.v)}">${esc(o.t)}</option>`).join('');
      return `<div class="field">
        <label for="f_${name}">${esc(label)}${req ? ' <span class="req" aria-hidden="true">*</span>' : ''}</label>
        <select id="f_${name}" name="${name}" ${req ? 'aria-required="true"' : ''}>${opts}</select>
        <span class="field-err" id="e_${name}"></span></div>`;
    }
    // Team dropdown, grouped by division section. Each option carries the section's first-listed
    // broker as its senior (data-senior / data-senior-email) so the Senior fields auto-fill on
    // change. Options are injected after render once divisions.json has loaded (fillTeamOptions).
    function teamField(name, label, req) {
      return `<div class="field">
        <label for="f_${name}">${esc(label)}${req ? ' <span class="req" aria-hidden="true">*</span>' : ''}</label>
        <select id="f_${name}" name="${name}" ${req ? 'aria-required="true"' : ''}>
          <option value="">Loading teams…</option></select>
        <span class="field-err" id="e_${name}"></span></div>`;
    }

    function renderForm() {
      const common =
        fieldText('name', 'Full name', { required: true }) +
        fieldText('id_number', 'ID number', { required: true }) +
        // Nationality is revealed + required only when the ID is not a 13-digit SA ID (i.e. a foreign
        // passport). For non-SA starters this pairs with a required work-permit upload on the FICA page.
        `<div class="field" id="nationalityWrap" hidden>
          <label for="f_nationality">Nationality <span class="req" aria-hidden="true">*</span></label>
          <input id="f_nationality" name="nationality" type="text" placeholder="e.g. Zimbabwean" autocomplete="off">
          <span class="field-err" id="e_nationality" aria-live="polite"></span></div>` +
        fieldText('contact', 'Cell number', { required: true, type: 'tel' }) +
        fieldText('email', 'Personal email', { required: true, type: 'email', hint: 'Used to send the contract + induction pack.' }) +
        fieldText('start_date', 'Start date', { required: true, type: 'date' });

      const quay1 =
        // Broker activity drives BOTH the {{BROKER_ACTIVITY}} clause and the Sale-vs-Rental
        // template (rent_* -> Rental), so a separate deal_type field is no longer needed.
        fieldSelect('activity', 'Broker activities',
          [{ v: '', t: '- select activity -' }].concat(BROKER_ACTIVITIES.map((a) => ({ v: a.code, t: a.label }))),
          true) +
        teamField('team', 'Team', true) +
        fieldText('senior_name', 'Reporting senior (name)', { placeholder: 'auto-fills from team - editable' }) +
        fieldText('senior_email', 'Reporting senior (email)', { type: 'email' }) +
        fieldText('commission', 'Commission %', { required: true, hint: 'e.g. 50 / 60 / 70' });

      const aqua =
        fieldSelect('agreement_type', 'Agreement type', [
          { v: 'monthly', t: 'Monthly' }, { v: 'fixed', t: 'Fixed term' }, { v: 'permanent', t: 'Permanent' },
        ], true) +
        fieldText('designation', 'Role / designation', { required: true }) +
        // end_date is required for a fixed-term MOA; shown only when agreement_type=fixed.
        `<div class="field" id="endDateWrap" hidden>
          <label for="f_end_date">End date <span class="req" aria-hidden="true">*</span></label>
          <input id="f_end_date" name="end_date" type="date">
          <span class="field-err" id="e_end_date" aria-live="polite"></span></div>` +
        fieldText('work_hours', 'Work hours', { hint: 'e.g. Mon to Fri, 08:00 to 17:00' }) +
        fieldText('remuneration', 'Remuneration', { hint: 'Monthly package or rate.' });

      // Provisioning systems: core three checked by default; cma/dialfire off (tick as needed).
      const systems = SYSTEMS.map((s) => `<label class="check">
        <input type="checkbox" name="sys_${s.key}" value="${s.key}" ${s.core ? 'checked' : ''}>
        <span><span class="ck-label">${esc(s.label)}</span><span class="ck-sub">${esc(s.sub)}</span></span>
      </label>`).join('');

      const canOnboard = USER && USER.canOnboard;
      const brokerOnly = USER && USER.isBroker && !USER.isSuper && !USER.isAdmin;
      const gate = !canOnboard
        ? `<div class="notice notice-warn">You do not have permission to submit an onboarding request.</div>`
        : brokerOnly
          ? `<div class="notice notice-info">You are submitting as ${esc(USER.name || 'yourself')}. The request is logged under your name; a super or admin oversees account provisioning.</div>`
          : '';

      const roleTitle = entity === 'aqua' ? 'Agreement' : 'Role and contract';
      form.innerHTML = `
        <div class="fieldset">
          <h3 class="fs-title">Person</h3>
          <div class="field-grid">${common}</div>
        </div>
        <div class="fieldset">
          <h3 class="fs-title">${roleTitle}</h3>
          <div class="field-grid">${entity === 'aqua' ? aqua : quay1}</div>
        </div>
        <div class="fieldset">
          <h3 class="fs-title">Provisioning</h3>
          <div class="check-grid">${systems}</div>
        </div>
        ${gate}
        <div class="form-actions">
          <button type="submit" class="btn btn-primary" id="obSubmit" ${canOnboard ? '' : 'disabled'}>Create contract</button>
          <button type="reset" class="btn btn-ghost">Clear</button>
        </div>`;

      // Provisioning checkboxes style their checked state via CSS (.check:has(input:checked)),
      // so no JS class toggle is needed here.
      // Quay 1: populate the Team dropdown from divisions.json and auto-fill the senior broker.
      // Both senior fields are editable and auto-fill on team change WITHOUT clobbering a manual
      // edit. If the directory can't load (or is empty), the Team select degrades to a free-text
      // input so onboarding is never blocked by a missing/lagging data file.
      const teamSel = form.querySelector('select[name="team"]');
      if (teamSel && entity !== 'aqua') {
        const seniorName = $('#f_senior_name', form), seniorEmail = $('#f_senior_email', form);
        // Clear the auto-fill flag as soon as the user types their own value.
        seniorName && seniorName.addEventListener('input', () => { seniorName.dataset.auto = ''; });
        seniorEmail && seniorEmail.addEventListener('input', () => { seniorEmail.dataset.auto = ''; });
        const autoFill = (field, val) => {
          if (field && (!field.value || field.dataset.auto === '1')) { field.value = val; field.dataset.auto = '1'; }
        };
        loadDivisions().then((d) => {
          if (!form.isConnected) return;               // view switched away while loading
          if (!d.sections || !d.sections.length) { degradeTeamToText(teamSel); return; }
          fillTeamOptions(teamSel, d);
          teamSel.addEventListener('change', () => {
            const opt = teamSel.selectedOptions[0];
            autoFill(seniorName, (opt && opt.dataset.senior) || '');
            autoFill(seniorEmail, (opt && opt.dataset.seniorEmail) || '');
          });
        });
      }
      // Aqua fixed-term reveals the required end_date field.
      const agr = form.querySelector('select[name="agreement_type"]');
      if (agr) {
        const endWrap = $('#endDateWrap', form), endInput = $('#f_end_date', form);
        const syncEnd = () => {
          const fixed = agr.value === 'fixed';
          if (endWrap) endWrap.hidden = !fixed;
          if (endInput) {
            if (fixed) { endInput.setAttribute('aria-required', 'true'); }
            else { endInput.removeAttribute('aria-required'); endInput.removeAttribute('aria-invalid'); }
          }
        };
        syncEnd(); agr.addEventListener('change', syncEnd);
      }
      // A non-SA ID (not exactly 13 digits) reveals the required Nationality field; a 13-digit SA ID
      // hides it. Mirrors the Aqua fixed-term end_date reveal so validation picks it up automatically.
      const idInput = $('#f_id_number', form);
      const natWrap = $('#nationalityWrap', form), natInput = $('#f_nationality', form);
      const syncNat = () => {
        // Reveal ONLY once a non-empty ID that is NOT a 13-digit SA ID is entered (an empty field
        // must not show Nationality; a 13-digit SA ID hides it).
        const idVal = ((idInput && idInput.value) || '').trim();
        const foreign = idVal.length > 0 && !/^\d{13}$/.test(idVal);
        if (natWrap) natWrap.hidden = !foreign;
        if (natInput) {
          if (foreign) { natInput.setAttribute('aria-required', 'true'); }
          else {
            natInput.removeAttribute('aria-required'); natInput.removeAttribute('aria-invalid');
            natInput.value = '';   // don't ship a stale "Zimbabwean" for a corrected 13-digit SA ID
            const e = $('#e_nationality', form); if (e) e.textContent = '';
          }
        }
      };
      if (idInput) { syncNat(); idInput.addEventListener('input', syncNat); }
    }

    form.addEventListener('submit', (e) => { e.preventDefault(); submitOnboard(form, entity); });
    renderForm();
    root.appendChild(wrap);
  }

  function collect(form) {
    const out = {};
    form.querySelectorAll('input, select').forEach((i) => {
      if (i.type === 'checkbox') return;
      out[i.name] = i.value.trim();
    });
    return out;
  }

  // Format checks beyond "not empty", keyed by field name. Return an error string, or '' if fine.
  // Only applied to a field once it has a value (emptiness is handled by the required check).
  function fieldFormatError(name, value) {
    const v = value.trim();
    if (!v) return '';
    if (name === 'candidate_email' || name === 'email' || name === 'senior_email') {
      return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v) ? '' : 'Enter a valid email address.';
    }
    // id_number is left to a not-empty check only: SA IDs, foreign passports (all-digit or
    // alphanumeric, varying lengths) are all valid here, so a strict format check falsely blocks people.
    if (name === 'commission') {
      return /^\d{1,3}(\.\d+)?$/.test(v) && Number(v) <= 100 ? '' : 'Enter a number between 0 and 100.';
    }
    return '';
  }

  function validateOnboard(form) {
    let firstBad = null;
    const mark = (i, msg) => {
      const errEl = $('#e_' + i.name, form);
      i.setAttribute('aria-invalid', msg ? 'true' : 'false');
      if (errEl) errEl.textContent = msg || '';
      if (msg && !firstBad) firstBad = i;
    };
    form.querySelectorAll('[aria-required="true"]').forEach((i) => {
      mark(i, !i.value.trim() ? 'Required.' : fieldFormatError(i.name, i.value));
    });
    // Optional fields still get a format check when filled (e.g. senior email).
    form.querySelectorAll('input:not([aria-required="true"])').forEach((i) => {
      const msg = fieldFormatError(i.name, i.value || '');
      if (msg) mark(i, msg);
    });
    if (firstBad) firstBad.focus();
    return !firstBad;
  }

  async function submitOnboard(form, entity) {
    if (!validateOnboard(form)) { toast('Check the form', 'Some required fields are missing.', 'err'); return; }
    const data = collect(form);
    data.entity = entity;
    // Backend reads the provisioning selection under `systems` (CONTRACTS section 6).
    data.systems = SYSTEMS.map((s) => s.key).filter((k) => form.querySelector(`input[name="sys_${k}"]`).checked);
    data.requester_name = USER ? USER.name : '';
    data.requester_email = USER ? USER.email : '';

    const btn = $('#obSubmit', form);
    btn.classList.add('loading'); btn.disabled = true;
    try {
      const kind = entity === 'aqua' ? KINDS.onboardAqua : KINDS.onboardQuay1;
      const r = await api(kind, data);
      if (r && r.emailed === false) {
        toast('Onboarded, but the email did not send', `${data.name}'s record and contract are ready, but the welcome email failed to send. Use "Send reminder" on the Progress report to try again, or contact them directly.`, 'err');
      } else {
        toast('Onboarding submitted', `${data.name} has been emailed their agreement and a secure FICA link. Once their signed contract + FICA docs are in, an admin accepts them on the Admin Check tab to set up accounts.`, 'ok');
      }
      form.reset();
      // Restore check defaults: core systems on, optional systems off.
      form.querySelectorAll('.check input').forEach((i) => {
        const sys = SYSTEMS.find((s) => i.name === `sys_${s.key}`);
        i.checked = !!(sys && sys.core);
      });
      form.querySelectorAll('[aria-invalid]').forEach((i) => i.removeAttribute('aria-invalid'));
      if (r && r.folderId) statusCache = [];  // force a refresh next time status opens
    } catch (err) {
      toast('Could not submit', err.message, 'err');
    } finally {
      btn.classList.remove('loading'); btn.disabled = false;
    }
  }

  //  PROGRAMS - who on a team holds CMA + PropData accounts (role-scoped by the backend)
  function viewPrograms(root) {
    const wrap = el(`<div class="stack">
      <div class="section-head">
        <h2>Programs</h2>
        <p>CMA and PropData accounts per team, grouped by senior broker. You see every team you work in; supers and admins see everyone.</p>
      </div>
      <div class="card card-pad">
        <div class="toolbar">
          <div class="muted" id="progMeta">Loading...</div>
          <div class="toolbar-right">
            <button type="button" class="btn btn-ghost btn-sm" id="progRefresh">Refresh</button>
          </div>
        </div>
        <div class="notice notice-info">
          <span class="pill pill-done">✓ CMA</span> has a CMA account
          <span class="pill pill-running">Agent</span> full PropData agent
          <span class="pill pill-running">Spec #</span> property-specialist profile
          <span class="pill pill-skipped">inactive</span> inactive
          <span class="pill pill-skipped">no</span> none held
        </div>
        <div id="progBody"></div>
      </div>
    </div>`);
    root.appendChild(wrap);
    $('#progRefresh', wrap).addEventListener('click', () => loadPrograms(wrap, true));
    loadPrograms(wrap, false);
  }

  let programsCache = null;
  async function loadPrograms(wrap, force) {
    const body = $('#progBody', wrap), meta = $('#progMeta', wrap);
    body.innerHTML = `<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>`;
    meta.textContent = 'Loading...';
    // The first POST to a cold Apps Script /exec occasionally returns a non-JSON body
    // ("Bad response from server"); it always succeeds on a retry. So retry twice, briefly,
    // before surfacing an error - the user should not have to hit Refresh.
    try {
      if (programsCache && !force) { renderPrograms(body, meta, programsCache); return; }
      let r, lastErr;
      for (let attempt = 0; attempt < 3; attempt++) {
        try { r = await api(KINDS.programs, {}); lastErr = null; break; }
        catch (e) { lastErr = e; await new Promise((res) => setTimeout(res, 600)); }
      }
      if (lastErr) throw lastErr;
      programsCache = r;
      renderPrograms(body, meta, r);
    } catch (err) {
      meta.textContent = '';
      body.innerHTML = `<div class="state"><div class="state-title">Could not load Programs</div><div>${esc(err.message)}</div></div>`;
    }
  }

  const SCOPE_LABEL = { all: 'all teams', senior: 'your teams', self: 'your account' };
  function renderPrograms(body, meta, r) {
    const sections = (r && r.sections) || [];
    const teamCount = sections.reduce((n, s) => n + (s.teams ? s.teams.length : 0), 0);
    meta.textContent = sections.length ? `Showing ${SCOPE_LABEL[r.scope] || ''} · ${teamCount} team(s)` : '';
    if (!sections.length) {
      body.innerHTML = `<div class="state"><div class="state-title">Nothing to show</div><div>No team accounts are visible for your login yet.</div></div>`;
      return;
    }
    const pdPill = (pd) => {
      if (!pd) return `<span class="pill pill-skipped">no</span>`;
      const lbl = pd.type === 'agent' ? 'Agent' : `Spec #${esc(pd.number)}`;
      return `<span class="pill pill-running">${lbl}</span>` + (pd.active ? '' : `<span class="pill pill-skipped">inactive</span>`);
    };
    const cmaPill = (p) => p.cma ? `<span class="pill pill-done">✓ CMA</span>` : `<span class="pill pill-skipped">no</span>`;
    const rowHtml = (p) => `<div class="person-row${p.senior ? ' sr' : ''}">
        <span class="person-name">${p.senior ? '<span class="star">★</span>' : '<span class="star dim">·</span>'}${esc(p.name)}${p.isNew ? '<span class="pill pill-new">NEW</span>' : ''}${p.senior ? '<span class="senior-tag">SENIOR</span>' : ''}</span>
        ${cmaPill(p)}
        ${pdPill(p.pd)}
      </div>`;
    const teamHtml = (t) => {
      const n = t.people.length;
      const nc = t.people.filter((p) => p.cma).length;
      const np = t.people.filter((p) => p.pd).length;
      const head = t.name
        ? `<div class="card-head">
             <div><span class="team-name">${esc(t.name)}</span>${t.senior ? ` <span class="team-senior">★ ${esc(t.senior)}</span>` : ''}</div>
             <div><span class="bubble">${nc}/${n} CMA</span> <span class="bubble">${np}/${n} PropData</span></div>
           </div>`
        : '';
      return `<div class="team-card">${head}${t.people.map(rowHtml).join('')}</div>`;
    };
    body.innerHTML = sections.map((s) => `<div class="team-section">${esc(s.name)}</div>${s.teams.map(teamHtml).join('')}`).join('');
  }

  //  2. PROVISIONING STATUS
  function viewProvisioning(root) {
    const wrap = el(`<div class="stack">
      <div class="section-head">
        <h2>Progress report</h2>
        <p>Where every new hire stands: who you are waiting on for documents, who is ready for an admin to accept (on the Admin Check tab), and the account setup once accepted. Nothing is created until an admin accepts.</p>
      </div>
      <div class="card card-pad">
        <div class="toolbar">
          <div class="muted" id="provMeta">Loading...</div>
          <div class="toolbar-right">
            <button type="button" class="btn btn-ghost btn-sm" id="provRefresh">Refresh</button>
          </div>
        </div>
        <div id="pipeBody"></div>
        <div id="bookedBody"></div>
        <div id="provBody"></div>
      </div>
    </div>`);
    root.appendChild(wrap);
    $('#provRefresh', wrap).addEventListener('click', () => loadStatus(wrap, true));
    loadStatus(wrap, false);
  }

  const STATUS_CLASS = {
    pending: 'pill-pending', in_progress: 'pill-running', inprogress: 'pill-running',
    done: 'pill-done', error: 'pill-error', skipped: 'pill-skipped',
  };
  const STATUS_LABEL = {
    pending: 'Pending', in_progress: 'In progress', inprogress: 'In progress',
    done: 'Done', error: 'Error', skipped: 'Skipped',
  };

  async function loadStatus(wrap, force) {
    const pipe = $('#pipeBody', wrap), body = $('#provBody', wrap), meta = $('#provMeta', wrap);
    pipe.innerHTML = `<div class="skeleton"></div><div class="skeleton"></div>`;
    body.innerHTML = '';
    meta.textContent = 'Loading...';
    let r = null, lastErr = null;
    // A cold /exec can return non-JSON ("Bad response") on the first hit; retry only that case.
    // A timeout or auth error is real - surface it immediately rather than retrying for ~100s.
    for (let attempt = 0; attempt < 3; attempt++) {
      try { r = await api(KINDS.status, {}); lastErr = null; break; }
      catch (err) { lastErr = err; if (!/Bad response/.test(err.message)) break; }
    }
    if (lastErr) {
      meta.textContent = '';
      pipe.innerHTML = `<div class="state"><div class="state-title">Could not load the progress report</div><div>${esc(lastErr.message)}</div></div>`;
      return;
    }
    const rows = (r.rows || r.data || []).slice();       // provisioning queue (created systems)
    const pipeline = (r.onboarding || []).slice();       // candidates not yet set up
    statusCache = rows;
    renderPipeline(pipe, meta, pipeline, wrap);
    renderBooked($('#bookedBody', wrap), (r.booked || []));
    renderStatus(body, null, rows);
  }

  // Candidates who have booked an induction week: a compact list with a "Resend induction packet" button.
  function renderBooked(host, items) {
    if (!host) return;
    if (!items || !items.length) { host.innerHTML = ''; return; }
    const cards = items.map((o) => {
      const entTag = HUB.entTag(o.entity);
      const when = [o.induction_wed, o.induction_thu].filter(Boolean).map((d) => fmtNiceDate(d)).join(' & ');
      return `<div class="pipe-row">
        ${HUB.avatar(o.name, o.entity)}
        <div class="pipe-main">
          <div class="pipe-name">${esc(o.name || '(no name)')} ${entTag}</div>
          <div class="pipe-team">${esc(o.team || '')}${when ? ` · induction ${esc(when)}` : ''}</div>
        </div>
        <div class="pipe-side">
          <span class="pill pill-done">Induction booked</span>
          <div class="pipe-actions"><button type="button" class="btn btn-ghost btn-sm" data-resend="${esc(o.folderId)}" data-name="${esc(o.name || '')}">Resend induction packet</button></div>
        </div>
      </div>`;
    }).join('');
    host.innerHTML = `<div class="pipe-subhead">Induction booked</div><div class="pipe-list">${cards}</div>`;
    host.querySelectorAll('[data-resend]').forEach((b) => {
      b.addEventListener('click', async () => {
        const name = b.dataset.name || 'this person';
        b.classList.add('loading'); b.disabled = true;
        try {
          const r = await api(KINDS.resendPacket, { folderId: b.dataset.resend });
          toast('Induction packet resent', `The induction packet was resent to ${esc(name)}.`, 'ok');
          b.classList.remove('loading'); b.disabled = false;
        } catch (err) {
          toast('Could not resend packet', err.message, 'err');
          b.classList.remove('loading'); b.disabled = false;
        }
      });
    });
  }

  // Friendly date for the booked-induction line ('Wed 5 Aug' style); falls back to the raw value.
  function fmtNiceDate(iso) {
    const m = String(iso || '').match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (!m) return iso || '';
    const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${+m[3]} ${MON[+m[2] - 1]}`;
  }

  // Compact "3h ago" / "2d ago" from an ISO timestamp; '' if unparseable.
  function timeAgo(iso) {
    if (!iso) return '';
    const t = Date.parse(iso);
    if (isNaN(t)) return '';
    const s = Math.max(0, (Date.now() - t) / 1000);
    if (s < 90) return 'just now';
    const m = s / 60; if (m < 60) return `${Math.round(m)}m ago`;
    const h = m / 60; if (h < 24) return `${Math.round(h)}h ago`;
    return `${Math.round(h / 24)}d ago`;
  }

  // The candidate pipeline: who is waiting on docs, who is ready to approve, who is being set up.
  function renderPipeline(host, meta, items, wrap) {
    const awaiting = items.filter((o) => o.docs_ready && !o.approved).length;
    if (meta) meta.textContent = items.length
      ? `${items.length} in progress${awaiting ? ` · ${awaiting} ready to approve` : ''}` : '';
    if (!items.length) {
      host.innerHTML = `<div class="state"><div class="state-title">No one in progress</div><div>New hires appear here after onboarding, and stay until their accounts are set up.</div></div>`;
      return;
    }
    // Accept/approve now lives on the Admin Check tab (super/admin only). The Progress report is
    // view-only: it shows document + approval state and offers Send reminder, but never an Accept
    // button (that would 403 for non-admins and duplicate the Admin Check action).
    const docPill = HUB.docPill;
    const cards = items.map((o) => {
      const entTag = HUB.entTag(o.entity);
      const state = (o.approved && o.setup_error) ? { c: 'pill-error', t: 'Setup error · needs attention' }
        : (o.approved && o.setup_incomplete) ? { c: 'pill-running', t: 'Setting up accounts' }
        : o.approved ? { c: 'pill-done', t: 'Approved · setting up' }
        : o.docs_ready ? { c: 'pill-ready', t: 'Ready to approve' }
        : { c: 'pill-pending', t: 'Waiting on documents' };
      const docs = `<div class="docs">
        ${docPill(o.docs && o.docs.contract, 'Contract')}${docPill(o.docs && o.docs.id, 'ID')}
        ${docPill(o.docs && o.docs.poa, 'Address')}${docPill(o.docs && o.docs.bank, 'Bank')}</div>`;
      const remindBtn = !o.approved
        ? `<button type="button" class="btn btn-ghost btn-sm" data-remind="${esc(o.folderId)}" data-name="${esc(o.name || '')}" data-reminded="${esc(o.reminded_at || '')}">Send reminder</button>` : '';
      const remindedNote = o.reminded_at ? `<div class="pipe-reminded">Reminded ${esc(timeAgo(o.reminded_at))}</div>` : '';
      return `<div class="pipe-row">
        ${HUB.avatar(o.name, o.entity)}
        <div class="pipe-main">
          <div class="pipe-name">${esc(o.name || '(no name)')} ${entTag}</div>
          <div class="pipe-team">${esc(o.team || '')}</div>
          ${docs}
        </div>
        <div class="pipe-side">
          <span class="pill ${state.c}">${state.t}</span>
          <div class="pipe-actions">${remindBtn}</div>
          ${remindedNote}
        </div>
      </div>`;
    }).join('');
    host.innerHTML = `<div class="pipe-list">${cards}</div>`;
    wirePipeline(host, wrap);
  }

  function wirePipeline(host, wrap) {
    host.querySelectorAll('[data-remind]').forEach((b) => {
      b.addEventListener('click', async () => {
        const name = b.dataset.name || 'this person';
        const last = Date.parse(b.dataset.reminded || '');
        if (!isNaN(last) && (Date.now() - last) < 60 * 60 * 1000
            && !confirm(`${name} was already reminded less than an hour ago. Send another reminder?`)) return;
        b.classList.add('loading'); b.disabled = true;
        try {
          const r = await api(KINDS.remind, { folderId: b.dataset.remind });
          toast('Reminder sent', `A follow-up with the contract was sent to ${esc(r.to || name)}.`, 'ok');
          b.classList.remove('loading'); b.disabled = false;
        } catch (err) {
          toast('Could not send reminder', err.message, 'err');
          b.classList.remove('loading'); b.disabled = false;
        }
      });
    });
  }

  function renderStatus(body, meta, rows) {
    if (!rows.length) {
      if (meta) meta.textContent = '';
      body.innerHTML = '';   // the pipeline above already shows in-progress candidates
      return;
    }
    const canRetry = USER && USER.isSuper;
    if (meta) meta.textContent = `${rows.length} queue row(s)`;
    const heading = `<div class="pipe-subhead">Account setup</div>`;
    const head = `<thead><tr>
      <th>Person</th><th>Entity</th><th>System</th><th>Action</th><th>Status</th><th>Detail</th>
      ${canRetry ? '<th aria-label="Retry"></th>' : ''}</tr></thead>`;
    const trs = rows.map((row) => {
      const st = String(row.status || 'pending').toLowerCase().replace(/\s+/g, '_');
      const cls = STATUS_CLASS[st] || 'pill-pending';
      const lbl = STATUS_LABEL[st] || row.status || 'Pending';
      const ent = (row.entity || '').toLowerCase();
      const entTag = ent === 'aqua' ? '<span class="tag-entity tag-aqua">Aqua</span>'
        : ent === 'quay1' ? '<span class="tag-entity tag-quay1">Quay 1</span>' : '<span class="muted">-</span>';
      const detail = row.result_json && typeof row.result_json === 'object'
        ? (row.result_json.username || row.result_json.id || row.result_json.error || '')
        : (row.result_json || row.detail || '');
      const retryCell = canRetry
        ? `<td class="actions">${(st === 'error') ? `<button type="button" class="btn btn-ghost btn-sm" data-retry="${esc(row.queue_id || '')}">Retry</button>` : ''}</td>`
        : '';
      return `<tr>
        <td class="who">${esc(row.full_name || row.name || '')}</td>
        <td>${entTag}</td>
        <td class="sys">${esc(row.system || '')}</td>
        <td class="sys">${esc(row.action || 'create')}</td>
        <td><span class="pill ${cls}">${esc(lbl)}</span></td>
        <td class="muted">${esc(detail).slice(0, 80)}</td>
        ${retryCell}</tr>`;
    }).join('');
    body.innerHTML = heading + `<div class="tbl-wrap"><table class="tbl">${head}<tbody>${trs}</tbody></table></div>`;

    if (canRetry) {
      body.querySelectorAll('[data-retry]').forEach((b) => {
        b.addEventListener('click', async () => {
          b.classList.add('loading'); b.disabled = true;
          try {
            await api(KINDS.retry, { queue_id: b.dataset.retry });
            toast('Retry queued', 'The worker will pick this row up again.', 'ok');
            statusCache = [];
            loadStatus(body.closest('.stack'), true);
          } catch (err) {
            toast('Retry failed', err.message, 'err');
            b.classList.remove('loading'); b.disabled = false;
          }
        });
      });
    }
  }

  //  AUTH BOOT (login gate + session)
  function initLoginGate() {
    const gate = $('#loginGate'), userInput = $('#loginUser'), dots = $('#pinDots'),
          errEl = $('#loginError'), pad = $('#loginKeypad');
    let pin = '';
    const paint = () => dots.querySelectorAll('.pin-dot').forEach((d, i) => d.classList.toggle('filled', i < pin.length));
    const showErr = (m) => { errEl.textContent = m; errEl.hidden = false; gate.classList.add('pin-error'); setTimeout(() => gate.classList.remove('pin-error'), 500); };

    async function attempt() {
      const u = userInput.value.trim();
      if (!u) { showErr('Enter your username.'); return; }
      errEl.hidden = true;
      const r = await window.AUTH.signIn(u, pin);
      pin = ''; paint();
      if (!r.ok) { showErr(r.error || 'Sign-in failed.'); return; }
      USER = r.user; onSignedIn();
    }
    pad.addEventListener('click', (e) => {
      const b = e.target.closest('button'); if (!b) return;
      if (b.hasAttribute('data-clear')) { pin = ''; paint(); return; }
      if (b.hasAttribute('data-back')) { pin = pin.slice(0, -1); paint(); return; }
      if (b.dataset.d && pin.length < 6) { pin += b.dataset.d; paint(); if (pin.length === 6) attempt(); }
    });
    document.addEventListener('keydown', (e) => {
      if (document.body.classList.contains('pre-auth') === false) return;
      if (e.key >= '0' && e.key <= '9' && pin.length < 6) { pin += e.key; paint(); if (pin.length === 6) attempt(); }
      else if (e.key === 'Backspace' && document.activeElement !== userInput) { pin = pin.slice(0, -1); paint(); }
      else if (e.key === 'Enter' && pin.length === 6) attempt();
    });
  }

  function onSignedIn() {
    document.body.classList.remove('pre-auth');
    const gate = $('#loginGate'); if (gate) gate.remove();  // uncover the app shell
    // Shared cross-app switcher on the Quay 1 flag (superusers only; no-op else).
    if (window.QuayNav) window.QuayNav.mount({ isSuper: !!(USER && USER.isSuper), current: 'boarding' });
    const so = $('#signOutBtn'); so.hidden = false;
    $('#signOutWho').textContent = USER && USER.name ? USER.name + ' - ' : '';
    so.addEventListener('click', async () => { await window.AUTH.signOut(); location.reload(); }, { once: true });
    // Offboarding: super/admin get the full destructive teardown tree; a broker gets a simple
    // "Request offboarding" form (notify only). Everyone with tool access can open the tab.
    if (!(USER && USER.canOnboard)) {
      // Remove both the top tab and its mobile bottom-nav twin.
      document.querySelectorAll('[data-tab="offboard"]').forEach((n) => n.remove());
    }
    // Admin Check (accept FICA) is super/admin only - remove the tab (and bottom-nav twin) for everyone else.
    if (!canAdminCheck()) {
      document.querySelectorAll('[data-tab="admincheck"]').forEach((n) => n.remove());
    }
    document.querySelectorAll('.tab-btn').forEach((b) => b.addEventListener('click', () => route(b.dataset.tab)));
    // Mobile bottom nav (index.html) routes through the same handler.
    document.querySelectorAll('.bottom-nav a[data-tab]').forEach((a) => {
      a.addEventListener('click', (e) => { e.preventDefault(); route(a.dataset.tab); });
    });
    route('onboard');
  }

  async function boot() {
    document.body.classList.add('pre-auth');
    initLoginGate();
    try {
      const u = await window.AUTH.getSession();
      if (u) { USER = u; onSignedIn(); }
    } catch (_) { /* stay on the gate */ }
  }

  document.addEventListener('DOMContentLoaded', boot);
})();
